<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 2,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 999,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 3,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 999,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 323.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 4,
            'title' => 'Sample Title2',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 999,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 31323.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('items')->insert([
            'user_id' => 1,
            'category_id' => 1,
            'title' => 'Sample Title',
            'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

            'location' => 'Sample Location',
            'mail' => 'sample@email.com',
            'phone' => '123456789',
            'price' => 1000.00,
            'type' => 'SUV',
            'brand' => 'Sample Brand',
            'fuel' => 'Gasoline',
            'mileage' => 50000.0,
            'active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
    }
}
